name: physics
author: Marcus Wendt <marcus@field.io>
version: 0.0.6
homepage: https://github.com/field/physics.dart
description: 2D + 3D Particle Physics Simulation for Dart
dependencies:
  vector_math: '>=1.4.2+1 <2.0.0'
