name: physics
version: 0.0.19
author: Marcus Wendt <marcus@field.io>
description: 2D + 3D Particle Physics Simulation for Dart
homepage: https://github.com/field/physics.dart
dependencies:
  vector_math: '>=1.4.2+1'
